# Generated by Django 3.1 on 2020-08-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DndClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('spell_list', models.ManyToManyField(to='spell.Spell')),
            ],
        ),
    ]
