# Generated by Django 3.1 on 2020-08-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0001_initial'),
        ('dnd_class', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dndclass',
            name='spell_list',
            field=models.ManyToManyField(blank=True, null=True, to='spell.Spell'),
        ),
    ]
