# Generated by Django 3.1 on 2020-08-19 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_class', '0002_auto_20200819_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dndclass',
            options={'verbose_name': 'DnD Class', 'verbose_name_plural': 'DnD Classes'},
        ),
    ]
