# Generated by Django 3.1 on 2020-08-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('text', models.TextField()),
                ('school', models.CharField(max_length=255)),
                ('casting_time', models.CharField(max_length=255)),
                ('range', models.CharField(max_length=255)),
                ('materials', models.CharField(max_length=255)),
                ('components', models.TextField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
            ],
        ),
    ]
