# Generated by Django 3.1 on 2020-08-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spell',
            options={'verbose_name': 'Spell', 'verbose_name_plural': 'Spells'},
        ),
        migrations.AlterField(
            model_name='spell',
            name='components',
            field=models.CharField(max_length=255),
        ),
    ]
