# Generated by Django 3.1 on 2020-08-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0003_auto_20200819_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='concentration',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='ritual',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
