# Generated by Django 3.1 on 2020-08-20 09:26

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0004_auto_20200819_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='materials_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='test_components',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('V', 'Verbal'), ('S', 'Somatic'), ('M', 'Material')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
