# Generated by Django 3.1 on 2020-08-20 09:42

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0005_auto_20200820_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='test_components',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('V', 'Verbal'), ('S', 'Somatic'), ('M', 'Material')], max_length=5, null=True),
        ),
    ]
