# Generated by Django 3.1 on 2020-08-20 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0007_auto_20200820_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='components',
        ),
    ]
