# Generated by Django 3.1 on 2020-08-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0009_auto_20200820_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='school',
            field=models.CharField(blank=True, choices=[('IL', 'Illusion'), ('EN', 'Enchantment'), ('DV', 'Divination'), ('NC', 'Necromancy'), ('EV', 'Evocation'), ('CN', 'Conjuration'), ('TR', 'Transmutation'), ('AB', 'Abjuration')], max_length=2, null=True),
        ),
    ]
