# Generated by Django 3.1.2 on 2020-10-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0010_auto_20200820_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('V', 'Verbal'), ('S', 'Somatic'), ('M', 'Material')], max_length=1, unique=True)),
            ],
            options={
                'verbose_name': 'Component',
                'verbose_name_plural': 'Components',
            },
        ),
        migrations.RemoveField(
            model_name='spell',
            name='components',
        ),
        migrations.AddField(
            model_name='spell',
            name='components',
            field=models.ManyToManyField(blank=True, null=True, to='spell.Component'),
        ),
    ]
