# Generated by Django 3.1.2 on 2020-10-16 11:16

from django.db import migrations


def populate_components(apps, schema_editor):
	Component = apps.get_model('spell', 'Component')
	components_list = ['V', 'S', 'M']
	for component in components_list:
		Component.objects.get_or_create(name=component)


def remove_components(apps, schema_editor):
	Component = apps.get_model('spell', 'Component')
	Component.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0011_auto_20201016_1111'),
    ]

    operations = [
		migrations.RunPython(populate_components, remove_components)
    ]
