# Generated by Django 3.1.2 on 2020-10-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0012_populate_components'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='components',
            field=models.ManyToManyField(to='spell.Component'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='school',
            field=models.CharField(blank=True, choices=[('IL', 'Illusion'), ('EN', 'Enchantment'), ('DV', 'Divination'), ('NC', 'Necromancy'), ('EV', 'Evocation'), ('CN', 'Conjuration'), ('TR', 'Transmutation'), ('AB', 'Abjuration')], max_length=20, null=True),
        ),
    ]
