# Generated by Django 3.1.2 on 2020-10-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0013_auto_20201016_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='materials',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='materials_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='school',
            field=models.CharField(blank=True, choices=[('IL', 'Illusion'), ('EN', 'Enchantment'), ('DV', 'Divination'), ('NC', 'Necromancy'), ('EV', 'Evocation'), ('CN', 'Conjuration'), ('TR', 'Transmutation'), ('AB', 'Abjuration')], max_length=2, null=True),
        ),
    ]
